export type ApiError =
    "POLLIT:AUTH:CREDENTIALS_SIGNIN_FAILED" |
    "POLLIT:AUTH:EMAIL_ALREADY_EXISTS" |
    "POLLIT:AUTH:EXPIRED_ACCESS_TOKEN_IS_INVALID" |
    "POLLIT:AUTH:FORBIDDEN_ACCESS" |
    "POLLIT:AUTH:GOOGLE_SIGNIN_FAILED" |
    "POLLIT:AUTH:INVALID_EMAIL" |
    "POLLIT:AUTH:INVALID_USER_NAME" |
    "POLLIT:AUTH:PASSWORD_DOES_NOT_MEET_REQUIREMENTS" |
    "POLLIT:AUTH:REFRESH_TOKEN_IS_INVALID" |
    "POLLIT:AUTH:USER_NAME_ALREADY_EXISTS" |
    "POLLIT:COMMENTS:COMMENT_NOT_FOUND" |
    "POLLIT:COMMENTS:PARENT_COMMENT_IS_DELETED" |
    "POLLIT:POLLS:OPTION_TITLE_TOO_LONG" |
    "POLLIT:POLLS:OPTIONS_COUNT_SHOULD_BE_HIGHER_THAN_TWO" |
    "POLLIT:POLLS:OPTIONS:OPTION_NOT_FOUND" |
    "POLLIT:POLLS:POLL_NOT_FOUND" |
    "POLLIT:POLLS:TITLE_TOO_LONG" |
    "POLLIT:POLLS:TITLE_TOO_SHORT" |
    "POLLIT:POLLS:USER_HAS_ALREADY_VOTED_FOR_THIS_POLL" |
    "POLLIT:UNKOWN_ERROR" |
    "POLLIT:USERS:BIRTHDATE_IS_IN_THE_FUTURE" |
    "POLLIT:USERS:BIRTHDATE_IS_MALFORMED" |
    "POLLIT:USERS:USER_NAME_IS_ALREADY_PERMANENT" |
    "POLLIT:USERS:USER_NOT_FOUND";

