export type ApiError =
    'POLLIT:AUTH:CREDENTIALS_SIGNIN_FAILED' |
    'POLLIT:AUTH:EMAIL_ALREADY_EXISTS' |
    'POLLIT:AUTH:FORBIDDEN_ACCESS' |
    'POLLIT:AUTH:GOOGLE_SIGNIN_FAILED' |
    'POLLIT:AUTH:INVALID_EMAIL' |
    'POLLIT:AUTH:INVALID_USER_NAME' |
    'POLLIT:AUTH:PASSWORD_DOES_NOT_MEET_REQUIREMENTS' |
    'POLLIT:AUTH:USER_NAME_ALREADY_EXISTS' |
    'POLLIT:UNKOWN_ERROR' |
    'POLLIT:USERS:USER_NAME_IS_ALREADY_PERMANENT' |
    'POLLIT:USERS:USER_NOT_FOUND';
